# Generated by Django 3.2.9 on 2021-11-12 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Имя исполнителя')),
                ('country', models.CharField(max_length=64, verbose_name='Страна')),
                ('record_label', models.CharField(max_length=64, null=True, verbose_name='Звукозаписывающий лейбл')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Жанр')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название песни')),
                ('date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата выхода')),
                ('text', models.CharField(max_length=1024, verbose_name='Текст песни')),
                ('author_id', models.ManyToManyField(related_name='songs', to='songs.Author')),
                ('genre_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='songs.genre')),
            ],
        ),
    ]
