# Generated by Django 3.2.9 on 2021-11-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='text',
            field=models.CharField(max_length=1024, null=True, verbose_name='Текст песни'),
        ),
    ]
