# Generated by Django 3.2.9 on 2021-11-26 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_auto_20211119_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='date',
            field=models.DateField(default=datetime.date(2021, 11, 26), null=True, verbose_name='Дата выхода'),
        ),
    ]
