# Generated by Django 3.2.9 on 2021-11-12 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_alter_song_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='author_id',
            new_name='author',
        ),
    ]
