# Generated by Django 3.2.9 on 2021-12-05 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_alter_song_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='date',
            field=models.DateField(default=datetime.date(2021, 12, 5), null=True, verbose_name='Дата выхода'),
        ),
    ]
